# Generated by Django 2.0.5 on 2018-06-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_live',
            new_name='active',
        ),
    ]
